server:
  port: 9999
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9980/eureka,http://${eureka.instance.hostname}:9990/eureka