server:
  port: 9989
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lcssxl/RedBullStudio
#          uri: https://git.oschina.net/lcssxl/SpringCloudProject
#          username: ******
#          password: *****
#          searchPaths: documents
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9980/eureka,http://${eureka.instance.hostname}:9990/eureka