server:
  port: 9990
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9980/eureka,http://${eureka.instance.hostname}:9990/eureka