server:
  port: 9980
eureka:
  instance:
    hostname: EurekaServer1 #Eureka实例的主机名
  client:
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://EurekaServer2:9990/eureka